FROM python:3.11-slim
WORKDIR /app

# System dependencies for FAISS
RUN apt-get update && apt-get install -y libgomp1 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# This copies everything from your backend folder into the container
COPY . .

# Hugging Face uses port 7860
EXPOSE 7860
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7860"]
